In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_pickle('data/float.pkl')

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
int_rate,887379.0,13.246740,4.381867,5.32,9.990,12.990000,16.200000,2.899000e+01
loan_amnt,887379.0,14755.264605,8435.455601,500.00,8000.000,13000.000000,20000.000000,3.500000e+04
funded_amnt,887379.0,14741.877625,8429.897657,500.00,8000.000,13000.000000,20000.000000,3.500000e+04
dti,887379.0,18.157039,17.190626,0.00,11.910,17.650000,23.950000,9.999000e+03
total_rec_late_fee,887379.0,0.396692,4.087825,0.00,0.000,0.000000,0.000000,3.586800e+02
funded_amnt_inv,887379.0,14702.464383,8442.106732,0.00,8000.000,13000.000000,20000.000000,3.500000e+04
collection_recovery_fee,887379.0,4.880757,63.125281,0.00,0.000,0.000000,0.000000,7.002190e+03
recoveries,887379.0,45.919243,409.693874,0.00,0.000,0.000000,0.000000,3.352027e+04
installment,887379.0,436.717127,244.186593,15.67,260.705,382.550000,572.600000,1.445460e+03
revol_bal,887379.0,16920.787533,22426.791896,0.00,6443.000,11875.000000,20829.000000,2.904836e+06
last_pymnt_amnt,887379.0,2164.145585,4794.783233,0.00,280.170,462.780000,831.245000,3.647559e+04
out_prncp,887379.0,8403.124852,8493.450269,0.00,0.000,6458.290000,13659.055000,4.937286e+04
total_rec_prncp,887379.0,5757.706424,6625.441046,0.00,1200.570,3215.320000,8000.000000,3.500003e+04
out_prncp_inv,887379.0,8399.713242,8489.997617,0.00,0.000,6455.810000,13654.050000,4.937286e+04
total_rec_int,887379.0,1754.804327,2095.356099,0.00,441.460,1073.280000,2238.265000,2.420562e+04
total_pymnt_inv,887379.0,7521.160306,7846.108604,0.00,1899.700,4862.010000,10565.690000,5.777758e+04
total_pymnt,887379.0,7558.826684,7871.243336,0.00,1914.590,4894.999117,10616.814231,5.777758e+04
annual_inc,887375.0,75027.587761,64698.300142,0.00,45000.000,65000.000000,90000.000000,9.500000e+06
acc_now_delinq,887350.0,0.004991,0.077625,0.00,0.000,0.000000,0.000000,1.400000e+01
inq_last_6mths,887350.0,0.694623,0.998448,0.00,0.000,0.000000,1.000000,3.300000e+01
delinq_2yrs,887350.0,0.314442,0.862244,0.00,0.000,0.000000,0.000000,3.900000e+01
pub_rec,887350.0,0.195307,0.582091,0.00,0.000,0.000000,0.000000,8.600000e+01
open_acc,887350.0,11.548469,5.317313,0.00,8.000,11.000000,14.000000,9.000000e+01
total_acc,887350.0,25.268026,11.840561,1.00,17.000,24.000000,32.000000,1.690000e+02
collections_12_mths_ex_med,887234.0,0.014380,0.134191,0.00,0.000,0.000000,0.000000,2.000000e+01
revol_util,886877.0,55.067693,23.834344,0.00,37.700,56.000000,73.600000,8.923000e+02

## Replace missing values with mean

In [5]:
df_fpmean = df.mean()

In [6]:
df_fpmean

int_rate                         13.246740
loan_amnt                     14755.264605
funded_amnt                   14741.877625
dti                              18.157039
total_rec_late_fee                0.396692
funded_amnt_inv               14702.464383
collection_recovery_fee           4.880757
recoveries                       45.919243
installment                     436.717127
revol_bal                     16920.787533
last_pymnt_amnt                2164.145585
out_prncp                      8403.124852
total_rec_prncp                5757.706424
out_prncp_inv                  8399.713242
total_rec_int                  1754.804327
total_pymnt_inv                7521.160306
total_pymnt                    7558.826684
annual_inc                    75027.587761
acc_now_delinq                    0.004991
inq_last_6mths                    0.694623
delinq_2yrs                       0.314442
pub_rec                           0.195307
open_acc                         11.548469
total_acc                        25.268026
collections_12_mths_ex_med        0.014380
revol_util                       55.067693
dtype: float64

In [7]:
np.sum(df.isnull())

int_rate                        0
loan_amnt                       0
funded_amnt                     0
dti                             0
total_rec_late_fee              0
funded_amnt_inv                 0
collection_recovery_fee         0
recoveries                      0
installment                     0
revol_bal                       0
last_pymnt_amnt                 0
out_prncp                       0
total_rec_prncp                 0
out_prncp_inv                   0
total_rec_int                   0
total_pymnt_inv                 0
total_pymnt                     0
annual_inc                      4
acc_now_delinq                 29
inq_last_6mths                 29
delinq_2yrs                    29
pub_rec                        29
open_acc                       29
total_acc                      29
collections_12_mths_ex_med    145
revol_util                    502
dtype: int64

In [8]:
for colname in df.columns:
    df[colname][df[colname].isnull()]=df_fpmean[colname]

In [7]:
np.sum(df.isnull())

int_rate                      0
loan_amnt                     0
funded_amnt                   0
dti                           0
total_rec_late_fee            0
funded_amnt_inv               0
collection_recovery_fee       0
recoveries                    0
installment                   0
revol_bal                     0
last_pymnt_amnt               0
out_prncp                     0
total_rec_prncp               0
out_prncp_inv                 0
total_rec_int                 0
total_pymnt_inv               0
total_pymnt                   0
annual_inc                    0
acc_now_delinq                0
inq_last_6mths                0
delinq_2yrs                   0
pub_rec                       0
open_acc                      0
total_acc                     0
collections_12_mths_ex_med    0
revol_util                    0
dtype: int64

In [9]:
df_fpmean.to_pickle('data/df_fpmean')

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
int_rate,887379.0,13.246740,4.381867,5.32,9.990,12.990000,16.200000,2.899000e+01
loan_amnt,887379.0,14755.264605,8435.455601,500.00,8000.000,13000.000000,20000.000000,3.500000e+04
funded_amnt,887379.0,14741.877625,8429.897657,500.00,8000.000,13000.000000,20000.000000,3.500000e+04
dti,887379.0,18.157039,17.190626,0.00,11.910,17.650000,23.950000,9.999000e+03
total_rec_late_fee,887379.0,0.396692,4.087825,0.00,0.000,0.000000,0.000000,3.586800e+02
funded_amnt_inv,887379.0,14702.464383,8442.106732,0.00,8000.000,13000.000000,20000.000000,3.500000e+04
collection_recovery_fee,887379.0,4.880757,63.125281,0.00,0.000,0.000000,0.000000,7.002190e+03
recoveries,887379.0,45.919243,409.693874,0.00,0.000,0.000000,0.000000,3.352027e+04
installment,887379.0,436.717127,244.186593,15.67,260.705,382.550000,572.600000,1.445460e+03
revol_bal,887379.0,16920.787533,22426.791896,0.00,6443.000,11875.000000,20829.000000,2.904836e+06
last_pymnt_amnt,887379.0,2164.145585,4794.783233,0.00,280.170,462.780000,831.245000,3.647559e+04
out_prncp,887379.0,8403.124852,8493.450269,0.00,0.000,6458.290000,13659.055000,4.937286e+04
total_rec_prncp,887379.0,5757.706424,6625.441046,0.00,1200.570,3215.320000,8000.000000,3.500003e+04
out_prncp_inv,887379.0,8399.713242,8489.997617,0.00,0.000,6455.810000,13654.050000,4.937286e+04
total_rec_int,887379.0,1754.804327,2095.356099,0.00,441.460,1073.280000,2238.265000,2.420562e+04
total_pymnt_inv,887379.0,7521.160306,7846.108604,0.00,1899.700,4862.010000,10565.690000,5.777758e+04
total_pymnt,887379.0,7558.826684,7871.243336,0.00,1914.590,4894.999117,10616.814231,5.777758e+04
annual_inc,887379.0,75027.587761,64698.154323,0.00,45000.000,65000.000000,90000.000000,9.500000e+06
acc_now_delinq,887379.0,0.004991,0.077624,0.00,0.000,0.000000,0.000000,1.400000e+01
inq_last_6mths,887379.0,0.694623,0.998431,0.00,0.000,0.000000,1.000000,3.300000e+01
delinq_2yrs,887379.0,0.314442,0.862230,0.00,0.000,0.000000,0.000000,3.900000e+01
pub_rec,887379.0,0.195307,0.582081,0.00,0.000,0.000000,0.000000,8.600000e+01
open_acc,887379.0,11.548469,5.317226,0.00,8.000,11.000000,14.000000,9.000000e+01
total_acc,887379.0,25.268026,11.840368,1.00,17.000,24.000000,32.000000,1.690000e+02
collections_12_mths_ex_med,887379.0,0.014380,0.134180,0.00,0.000,0.000000,0.000000,2.000000e+01
revol_util,887379.0,55.067693,23.827601,0.00,37.700,56.000000,73.600000,8.923000e+02

In [13]:
df.to_pickle('data/float.pkl')